[hugoVersion]
extended = false
min = "0.125.0"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "assets/scss/plugins/_clipboard.scss"
target = "assets/scss/plugins/_clipboard.scss"

[[mounts]]
source = "package.json"
target = "data/dnb/modder/renderhooks.json"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = '_vendor/github.com/zenorocha/clipboard.js/dist/clipboard.js'
target = 'assets/js/plugins/lib/clipboard.js'

# # clipboard.js - handling copy button on code blocks
# # see https://github.com/zenorocha/clipboard.js
# [[imports]]
# path = "github.com/zenorocha/clipboard.js"
# disable = false
# ignoreConfig = true
# ignoreImports = true

# [[imports.mounts]]
# source = 'dist/clipboard.js'
# target = 'assets/js/plugins/lib/clipboard.js'
