baseURL = "http://localhost:1414/"
languageCode = "en-us"
title = "YouTube Module Demo"

disableKinds = ["taxonomy", "RSS"]

[privacy.youtube]
  disable = false
  privacyEnhanced = true

[module]
  [[module.imports]]
    path = "github.com/davidsneighbour/hugo-modules/modules/youtube"
  [module.hugoVersion]
    extended = true

[params.dnb.youtube.apiparams]
  rel = 0
  controls = 1
