################################################################################
# hugo-giscus @see https://github.com/davidsneighbour/hugo-giscus
################################################################################
[dnb.giscus]
src = "https://giscus.app/client.js"
#dataRepo = "username/reponame"
#dataRepoId = "ABCDEFGHIJKLMNOPQSTUVXYZABCDEFGH"
#dataCategory = "Comments"
#dataCategoryId = "ABCDEFGHIJKLMNOPQRST"
dataMapping = "specific"
dataLoading = "lazy"
dataReactionsEnabled = "1"
dataEmitMetadata = "0"
dataInputPosition = "top"  # top, bottom
dataTheme = "dark" # dark_dimmed, dark, light, light_dimmed
# dataThemeType = "local" # if set and local then dataTheme is an URL
# de, en, es, fr, gsw, id, it, ja, ko, pl, ro, ru, tr, vi, zh-CN, zh-TW
dataLang = "en"
dataStrict="1"

[dnb.giscus.extended]
# require giscus.json setup
# https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md
origins = []
originsRegex = []
defaultCommentOrder = "oldest" # "oldest" (oldest to newest) or "newest"
